export const LOG_OUT = 'LOG_OUT';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const STADIUM_SET_ALL = 'STADIUM_SET_ALL';
export const STADIUM_SET_SINGLE = 'STADIUM_SET_SINGLE';
export const STADIUM_SET_DETAIL = 'STADIUM_SET_DETAIL';
export const STADIUM_SET_TOTAL_COUNT = 'STADIUM_SET_TOTAL_COUNT';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const REVIEW_SET_STADIUM = 'REVIEW_SET_STADIUM';

export const USER_SET_SINGLE = 'USER_SET_SINGLE';
export const USER_SET_CURRENT = 'USER_SET_CURRENT';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_FOLLOW = 'USER_UPDATE_FOLLOW';

export const SEARCH_SET = 'SEARCH_SET';

export const FOLLOW_SET_REVIEWS = 'FOLLOW_SET_REVIEWS';
