export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const STADIUM_SET_ALL = 'STADIUM_SET_ALL';
export const STADIUM_SET_SINGLE = 'STADIUM_SET_SINGLE';
export const STADIUM_SET_DETAIL = 'STADIUM_SET_DETAIL';
export const STADIUM_SET_SEARCH = 'STADIUM_SET_SEARCH';

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const REVIEW_SET_STADIUM = 'REVIEW_SET_STADIUM';

export const USER_SET_SINGLE = 'USER_SET_SINGLE';
export const USER_SET_CURRET = 'USER_SET_CURRET';
